name: tiyenda
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: 3.0.0
  barcode_widget: 2.0.3
  cached_network_image: ^3.3.1
  cloud_firestore: 4.13.1
  cloud_firestore_platform_interface: 6.0.5
  cloud_firestore_web: 3.8.5
  equatable: 2.0.5
  file_picker: 6.1.1
  firebase_analytics: 10.7.4
  firebase_analytics_platform_interface: 3.8.4
  firebase_analytics_web: 0.5.5+11
  firebase_auth: 4.15.2
  firebase_auth_platform_interface: 7.0.8
  firebase_auth_web: 5.8.11
  firebase_core: 2.24.2
  firebase_core_platform_interface: 5.0.0
  firebase_core_web: 2.10.0
  firebase_crashlytics: 3.4.8
  firebase_crashlytics_platform_interface: 3.6.16
  firebase_dynamic_links: 5.4.8
  firebase_dynamic_links_platform_interface: 0.2.6+16
  firebase_performance: 0.9.3+8
  firebase_performance_platform_interface: 0.1.4+16
  firebase_performance_web: 0.1.4+16
  flutter_animate: 4.1.1+1
  flutter_cache_manager: 3.3.1
  flutter_native_splash: 2.3.1
  flutter_plugin_android_lifecycle: 2.0.17
  flutter_spinkit: 5.2.0
  flutter_staggered_grid_view: 0.7.0
  font_awesome_flutter: 10.6.0
  from_css_color: 2.0.0
  go_router: 7.1.1
  google_fonts: 4.0.3
  google_nav_bar: 5.0.5
  google_sign_in: 6.1.5
  google_sign_in_android: 6.1.20
  google_sign_in_ios: 5.6.4
  google_sign_in_platform_interface: 2.4.2
  google_sign_in_web: 0.12.1
  intl: 0.18.1
  json_path: 0.6.2
  mime_type: 1.0.0
  page_transition: 2.1.0
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  photo_view: 0.14.0
  pin_code_fields: 8.0.1
  plugin_platform_interface: 2.1.6
  provider: 6.0.5
  rxdart: 0.27.7
  share_plus: 7.2.1
  shared_preferences: 2.2.2
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.4
  shared_preferences_platform_interface: 2.3.1
  shared_preferences_web: 2.2.1
  sign_in_with_apple: 4.3.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: 1.0.1
  smooth_page_indicator: 1.1.0
  sqflite: 2.2.6
  stream_transform: 2.1.0
  timeago: 3.2.2
  universal_io: 2.2.2
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  webview_flutter: 4.0.5
  webview_flutter_android: 3.3.1
  webview_flutter_platform_interface: 2.0.2
  webview_flutter_wkwebview: 3.1.1
  webviewx_plus: 0.3.3
  xml: 6.3.0
  csv: ^5.1.1
  flutter_secure_storage: ^9.0.0
  easy_debounce: ^2.0.3
  google_maps_flutter: ^2.5.3
  location: ^5.0.3
  permission_handler: ^8.1.6 # Optional for handling permissions
  pdf: ^3.6.0
  geolocator: ^11.0.0
  percent_indicator: ^4.2.3


dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.0
  image: 4.0.17
  lints: 3.0.0

  flutter_test:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
